   from clipper import Clipper

   # ... existing code ...

   def main():
       # ... existing code ...
       clipper = Clipper()
       clipped_content = clipper.clip(element)
       # ... existing code ...